/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "FREE-WiLi",
  "tagline": "Documentation",
  "favicon": "img/favicon.ico",
  "url": "https://docs.freewili.com",
  "baseUrl": "/",
  "organizationName": "freewili",
  "projectName": "FreeWili_WebDocs",
  "onBrokenLinks": "ignore",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/freewili/FreeWili_WebDocs/blob/main/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/freewili-social-card.jpg",
    "navbar": {
      "title": "FREE-WiLi",
      "logo": {
        "alt": "FREE-WiLi_Logo",
        "src": "img/logo.svg",
        "target": "_self"
      },
      "items": [
        {
          "href": "https://freewili.com/",
          "label": "Home",
          "position": "left",
          "className": "nav-link"
        },
        {
          "href": "https://github.com/freewili/FreeWili_WebDocs/tree/main",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Follow Us",
          "items": [
            {
              "html": "\n                  <a href=\"https://www.facebook.com/ICSFREEWILI/\" target=\"_blank\" rel=\"noopener noreferrer\">\n                    <i class=\"fab fa-facebook\"></i> Facebook\n                  </a>\n                "
            },
            {
              "html": "\n                  <a href=\"https://www.instagram.com/free_wili_/\" target=\"_blank\" rel=\"noopener noreferrer\">\n                    <i class=\"fab fa-instagram\"></i> Instagram\n                  </a>\n                "
            },
            {
              "html": "\n                  <a href=\"https://www.linkedin.com/company/freewili/about/\" target=\"_blank\" rel=\"noopener noreferrer\">\n                    <i class=\"fab fa-linkedin\"></i> LinkedIn\n                  </a>\n                "
            },
            {
              "html": "\n                  <a href=\"https://twitter.com/FREEWiL_i\" target=\"_blank\" rel=\"noopener noreferrer\">\n                    <img src=\"/img/x-twitter.svg\" alt=\"Twitter Icon\" class=\"x-twitter\"> Twitter\n                  </a>\n                "
            },
            {
              "html": "\n                  <a href=\"https://www.youtube.com/channel/UCSx1CmqjhiaWd3I42zJyuDw\" target=\"_blank\" rel=\"noopener noreferrer\">\n                    <i class=\"fab fa-youtube\"></i> YouTube\n                  </a>\n                "
            }
          ]
        },
        {
          "title": "Company",
          "items": [
            {
              "label": "About FREE-WiLi",
              "href": "#"
            },
            {
              "label": "Helpful Links",
              "to": "/helpful-links"
            },
            {
              "label": "FREE-WiLi Discord",
              "href": "https://discord.com/invite/XJRBUCX62z"
            },
            {
              "label": "Contact Us",
              "href": "https://freewili.com/contact/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "FREE-WiLi",
        "src": "/img/FreeWIli_trans.png",
        "href": "https://freewili.com/",
        "width": 160
      },
      "copyright": "Copyright © 2024 <a href=\"https://freewili.com/\" class=\"freewili-link\"> FREE-WiLi, Inc.</a>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "announcementBar": {
      "id": "freewili",
      "content": "Welcome to the  <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"#\">FREE-WiLi Documentation</a>, website! Discover guides and resources to help you get the most out of FREE-WiLi. ",
      "backgroundColor": "#ef393e",
      "textColor": "#fff",
      "isCloseable": true
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 2
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": []
  },
  "plugins": [
    [
      "P:\\workspace\\FreeWili_WebDocs\\node_modules\\docusaurus-lunr-search\\src\\index.js",
      {
        "indexBaseUrl": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
